### ISSUE TITLE
Some typos and dimension of KDE to be fixed

### ISSUE THREAD

**Issue by Aksingh4302** [AmanSarraf/Opensource-Buddy#11]
- please assign this issue to me 
![aCLNYSm](https://user-images.githubusercontent.com/92823423/194413692-96526469-a272-4ae5-9ae0-1dd7287b030e.png)

**Comment by AmanSarraf** [comment]
Hey @Aksingh4302 , I have assigned this issue to you , feel free to contribute and learn.

**Comment by AmanSarraf** [comment]
Hey @Aksingh4302 , I have assigned this issue to you , feel free to contribute and learn.
