### ISSUE TITLE
Beautify the community section

### ISSUE THREAD

**Issue by AmanSarraf** [AmanSarraf/Opensource-Buddy#19]
- add a card layout 
- add some hover animation
- keep account of the color-composition
page [reference](https://i.imgur.com/a6IwQlS.png)

**Comment by Maryam-Momoh** [comment]
Hello, i am interested in this particular task. Can i be assigned to it

**Comment by Maryam-Momoh** [comment]
I noticed a spelling error on the README.md file "Acknoledgement" instead of "Acknowledgment"

**Comment by AmanSarraf** [comment]
Thanks @Maryam-Momoh , go ahead and make the changes
