### ISSUE TITLE
Java image is broken

### ISSUE THREAD

**Issue by mwasifk** [AmanSarraf/Opensource-Buddy#23]
The image for Java does not show up and throws 403 error.

**Comment by mwasifk** [comment]
Please assign this to me

**Comment by AmanSarraf** [comment]
sure , /assign @mwasifk

**Comment by mwasifk** [comment]
I have submitted a pull request

**Comment by mwasifk** [comment]
I am worried about copyright claims and whatnot; please assign someone else to this issue.
