### ISSUE TITLE
Typographical mistake

### ISSUE THREAD

**Issue by Pranav-Rustagi** [AmanSarraf/Opensource-Buddy#26]
@AmanSarraf  In the "Why open source" section, the word "benefits" is misspelled. Could you please assign this issue to me?

**Comment by AmanSarraf** [comment]
Okay I'll assign this to you , could you also make the paragraphs more visible in the ```why open source``` section.
/assign @Pranav-Rustagi

**Comment by Pranav-Rustagi** [comment]
@AmanSarraf Sure thing
