### ISSUE TITLE
Need Some Hover effects to make it reactive and attentive to users

### ISSUE THREAD

**Issue by cleverhare** [AmanSarraf/Opensource-Buddy#37]
In simple words Just wanna add some hover effects :)

**Comment by cleverhare** [comment]
Assign this to me brother

**Comment by AmanSarraf** [comment]
hey @cleverhare , please be specific while raising any issue , Do mention, what feature or bug you want to work on , Then I shall assign this to you.

**Comment by cleverhare** [comment]
Ok
