### ISSUE TITLE
not properly responsive

### ISSUE THREAD

**Issue by Akshun-01** [AmanSarraf/Opensource-Buddy#43]
![image](https://user-images.githubusercontent.com/93793691/195979586-f5d43a29-6500-42c3-9fcb-177119030071.png)

![image](https://user-images.githubusercontent.com/93793691/195979595-3a30d442-6ec3-4fe8-96cc-8270beaf5e03.png)

The website is not fully responsive for all screen sizes... If you think we can work on it, please assign me the issue.

**Comment by AmanSarraf** [comment]
Thanks @Akshun-01 , for raising this Issue . I'll assign this to you, looking forward to your contribution.
/assign @Akshun-01 .

**Comment by Akshun-01** [comment]
hey @AmanSarraf , sorry for the delay. I got caught up in my college work. I read the code. couldn't figure out which CSS, scss file is for which part. No file is used as the main CSS for body, so that I can use it for making it responsive. could you help me out with that.
