### ISSUE TITLE
Emoji not Showing in Second Section

### ISSUE THREAD

**Issue by horizenight** [AmanSarraf/Opensource-Buddy#44]
The emoji does not render in the heading "WHAT IT MEANS TO CONTRIBUTE"

![Screenshot 2022-10-15 211658](https://user-images.githubusercontent.com/76839614/195995600-34a7fb2e-8304-4041-b850-8eea6ee47661.png)

Either remove the emoji or replace it with new attractive emoji 

Kindly assign this task to me !

**Comment by AmanSarraf** [comment]
sure, /assign @horizenight
