### ISSUE TITLE
No transition on home page button hover

### ISSUE THREAD

**Issue by cleverhare** [AmanSarraf/Opensource-Buddy#48]
There should be a transition on the button hover effect to make it look cool

**Comment by cleverhare** [comment]
I would like to work on this issue. Kindly assign this to me

**Comment by cleverhare** [comment]
hey @AmanSarraf  are you there ?

**Comment by AmanSarraf** [comment]
Hey @cleverhare , you can start working and Make PR I'll assign it to you.
/assign @cleverhare

**Comment by cleverhare** [comment]
Thanks a lot brother

**Comment by cleverhare** [comment]
Hey @AmanSarraf please I have completed the work please merge it today its really important
