### ISSUE TITLE
Link to be opened in new tab

### ISSUE THREAD

**Issue by Bishnukt** [AmanSarraf/Opensource-Buddy#49]
**The websites linked in the program section are opening in the same page, over the opensource-buddy window, it would be better if they open in a new tab. Assign me this one.**

![Screenshot from 2022-10-18 00-23-12](https://user-images.githubusercontent.com/87633659/196259033-88ee0987-7693-4350-b649-3f3c635a716f.png)

**Comment by Aditya-Narayan-Nayak** [comment]
Sure that would be great.

**Comment by AmanSarraf** [comment]
I have assigned this to you @Bishnukt

**Comment by Bishnukt** [comment]
> I have assigned this to you @Bishnukt

Thank u ❤️ @AmanSarraf
