### ISSUE TITLE
Invalid link in Program section

### ISSUE THREAD

**Issue by Bishnukt** [AmanSarraf/Opensource-Buddy#53]
Hey @AmanSarraf, while working on the issue #49, I found out that the added link for KDE is not valid. The given link is <a href="https://kde.in" target="_blank">kde.in</a>, while the valid one is <a href="https://kde.org" target="_blank">kde.org</a>.
So should I solve this with issue #49 pr or create another pr for this issue I m now creating.  

![Screenshot from 2022-10-20 21-48-56](https://user-images.githubusercontent.com/87633659/197003899-953c9a9a-5c91-4914-ac1c-2a0fca6384c3.png)

**Comment by AmanSarraf** [comment]
create a new issue, then work accordingly.
to reduce the review confusion make sure that
`One PR should address one issue only`

**Comment by AmanSarraf** [comment]
shall I assign this issue to you or shall we pass it to some beginner?

**Comment by AmanSarraf** [comment]
okay, I shall assign this to you.
/assign @Bishnukt
