### ISSUE TITLE
[Bug] Need to add program icon and correction the typo mistake

### ISSUE THREAD

**Issue by AmanKumar2626** [AmanSarraf/Opensource-Buddy#66]
![image](https://user-images.githubusercontent.com/92772172/197191797-fe227e20-0d24-47ee-80f1-316b44434564.png)

**Comment by AmanSarraf** [comment]
Thanks @AmanKumar2626 for raising this issue, I am assigning this to you.
/assign @AmanKumar2626.

! Please read the latest announcement in the README as well,Thankyou.

**Comment by Sathasivamthirumoorthi** [comment]
please assign this to me , i would like to work on this

**Comment by AmanSarraf** [comment]
Hey @Sathasivamthirumoorthi , I have already assigned this to @AmanKumar2626 , you need to wait or look for new issue that to be generated soon, thankyou
