### ISSUE TITLE
Resize the header background to properly fit in screen

### ISSUE THREAD

**Issue by AmanSarraf** [AmanSarraf/Opensource-Buddy#78]
**Is your feature request related to a problem? Please describe.**
The current background doesn't properly fits in screen and needs scroll

**Describe the solution you'd like**
To adjust the dimension so that the banner could fit the screen

**Describe alternatives you've considered**

**Additional context**
![2022-10-26_09-09](https://user-images.githubusercontent.com/90839355/197929652-2f0aadf8-f0e0-40b4-beef-58634f159c89.png)

**Comment by GitArya27** [comment]
please assign this issue to me

**Comment by GitArya27** [comment]
please assign this issue to me @AmanSarraf

**Comment by AmanSarraf** [comment]
Sure /assign @GitArya27
